### ISSUE TITLE
Colours no longer coming through

### ISSUE THREAD

**Issue by adamreisnz** [logdna/logger-node#28] opened 2020-10-28 02:14 UTC
Does the 2.x.x version of the NodeJS logger no longer support colours?
Everything is coming in mono and colours appear to be stripped from our logs.

With the old logger we were able to capture colours in our logs (e.g. using `chalk`)

**Comment by darinspivey** [comment] 2020-11-02 16:09
@adamreisnz, We might have to iterate a bit more on this.  I used your exact code, and cannot reproduce the issue on our staging or production servers.  I modified the test to use both loggers.  Can you try this version and confirm whether or not you're seeing the issue?

```javascript
const logdna = require('@logdna/logger');
const Logger = require('logdna')
const chalk = require('chalk');

//Setup logger
const key = '...';
const options = {
  env: 'production',
  hostname: 'io',
};

const logDNALogger = logdna.setupDefaultLogger(key, options);
const oldLogger = Logger.createLogger(key, options)

//We don't want these errors to crash the app
logDNALogger.on('error', (err) => {
  console.error(err)
});

//Construct a line to log
const level = 'trace';
const args = ['The logger says something', chalk.red('with other red text')];
const fromNew = chalk.cyan('new logger'.padEnd(12)) + args.join(' ');
const fromOld = chalk.cyan('old logger'.padEnd(12)) + args.join(' ');

logDNALogger.log(fromNew, {level});
oldLogger.log(fromOld, {level})

logDNALogger.flush()
Logger.flushAll()
``` 

![Screen Shot 2020-11-02 at 11 03 41 AM](https://user-images.githubusercontent.com/1874788/97890601-b9880400-1cfb-11eb-89ad-1713c4cfac34.png)

**Comment by adamreisnz** [comment] 2020-11-30 08:27
Yes I see the same with that code example.
So the problem with `trace` becoming `TRACE` is apparent, but the colour problem is not.

I will see if there is another reason for the colours not showing up.

**Comment by adamreisnz** [comment] 2020-11-30 08:37
Could there be something different when running the script on Heroku? When I update our production script to log in our dev environment, the logs also come into LogDNA with colours. However, when that same script is run on Heroku, it all becomes gray.

**Comment by adamreisnz** [comment] 2020-11-30 08:57
I cannot figure it out. Run the exact same script in my dev environment:

![image](https://user-images.githubusercontent.com/490562/100588538-de9d8000-3356-11eb-925d-39703579a3a8.png)

Run it on Heroku:

![image](https://user-images.githubusercontent.com/490562/100588578-ebba6f00-3356-11eb-9980-98ba31b9c0b3.png)

If I run the simple example on Heroku the colours come through fine as well.

Anything else we can try?

**Comment by adamreisnz** [comment] 2020-11-30 09:18
Managed to "fix" it by forcing chalk colour support by setting `chalk.level = 3`
Not sure why it chose to think it's not supported in this particular combination, but at least it solves it.

**Comment by darinspivey** [comment] 2020-11-30 21:54
We're glad you were able to (sort of) track the issue down and put together a fix.  That's certainly some strange behavior.  Closing this out.

**Comment by adamreisnz** [comment] 2020-12-01 20:10
Sorry, the capitalisation in the new version of the logger is still not addressed.

**Comment by darinspivey** [comment] 2020-12-01 20:32
Oh, sorry about that.  We didn't have any plans to address that.  The logging levels are capitalized for consistency.  Is there a particular reason why the upper case is a problem?

**Comment by adamreisnz** [comment] 2020-12-05 22:38
Well it wasn't done in the v1 logger, so just wondering why the change?
Personally I find it rather distracting and inconsistent with the rest of the lines, which are likely not going to be ALL CAPS.

If consistency for logging purposes was an issue, I probably would have preferred it to be all lower case?

Thanks.

**Comment by darinspivey** [comment] 2020-12-07 19:33
You have valid points, and certainly, this is a change from the previous version.  The assumption was that (amongst making validation easy) an upper-cased level would "stand out" more as a special word rather than not, but we apologize for generalizing this decision since it really is personal preference.

We're happy to address this an a feature enhancement if you'd like.  Our only request is that we close this issue since the capitalization wasn't the subject, and open a fresh issue for the capitalization.  Please feel free to do so, and we will take a look.  Closing this particular issue out as resolved.

Thanks!

**Closed by darinspivey** 2020-12-07 19:33 UTC

**Comment by adamreisnz** [comment] 2020-12-07 23:19
All good, and understood. Thanks.
